export const LOGIN_ACTION = {
    LOGIN_REQUEST: 'AUTH/LOGIN_REQUEST',
    LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
    LOGIN_FAILURE: 'AUTH/LOGIN_FAILURE',
    LOGIN_IS_LOADING: 'AUTH/LOGIN_IS_LOADING'
}

export const MASTER_DATA_ACTION = {
    MASTER_DATA_ACTION_REQUEST: 'MASTER_DATA/MASTER_DATA_ACTION_REQUEST',
    MASTER_DATA_ACTION_SUCCESS: 'MASTER_DATA/MASTER_DATA_ACTION_SUCCESS',
    MASTER_DATA_ACTION_FAILURE: 'MASTER_DATA/MASTER_DATA_ACTION_FAILURE',
}